# Generated by Django 4.1.7 on 2023-03-16 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_comment_post_alter_comment_user_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="post", unique_together={("title", "description")},
        ),
    ]
